### ISSUE TITLE
Compilation error in Standalone Mode (UE 5.1.1, plugin V1.4.7)

### ISSUE THREAD

**Issue by Nerwy** [GameTechDev/XeSSUnrealPlugin#10]
Hello, I just added this plugin to my project but when I try to launch the game in Standalone Mode, I get these errors that cause the game to break:
![image](https://github.com/GameTechDev/XeSSUnrealPlugin/assets/47084352/87fd9e0c-4f82-4825-bf53-4cec0856f641)
These issues do not seem to appear in PIE or packaged builds which is really strange.

**Comment by xessgamedev** [comment]
Please share a full log file.

**Comment by Nerwy** [comment]
Sorry, forgot to attach it, here is it: 
[XeSSIssue.log](https://github.com/user-attachments/files/15951362/XeSSIssue.log)

**Comment by xessgamedev** [comment]
The reason should be your Blueprint referring XeSS Blueprint is loaded before `XeSSBlueprint` module is loaded, which is "PostEngineInit".
You can try to load you Blueprint module later or load `XeSSBlueprint` module earlier.

**Comment by Nerwy** [comment]
This blueprint is called from the game instance in order to initialise the XeSS upscaler at game start, is there a way to force the plugin to load before everything else including the game instance? 
Even adding a delay inside the game instance before calling the function that contain the XeSS function does not work.

**Comment by xessgamedev** [comment]
You may try to edit `XeSS.uplugin` to set load phase of module `XeSS` and `XeSSBlueprint` to "PreDefault", then they will be loaded before `UGameInstance::Init()`.

**Comment by Nerwy** [comment]
With this change the plugin does not block the load of anything else as expected but now the plugin itself does not work anymore because of this error: 
![image](https://github.com/GameTechDev/XeSSUnrealPlugin/assets/47084352/583a0302-9591-427b-b0b2-3466de11fd78)
 
[EasyGameUI5_1_2.log](https://github.com/user-attachments/files/15958499/EasyGameUI5_1_2.log)

**Comment by xessgamedev** [comment]
Sorry, you're right. `FSceneViewExtensions::RegisterExtension` requires `GEngine` to be assigned, which is done in `FEngineLoop::Init()`, let me check any other solution.

**Comment by xessgamedev** [comment]
Please try `TempFix.zip`, just replace the same files.
NOTE: it is a temp fix for testing only, the final solution may change in the next public release.
[TempFix.zip](https://github.com/user-attachments/files/15963622/TempFix.zip)

**Comment by Nerwy** [comment]
Thank you for checking it out. Unfortunately this does not seem to work as now the engine crash on startup 
![image](https://github.com/GameTechDev/XeSSUnrealPlugin/assets/47084352/7f502179-37b7-4d32-8a80-ae478d261cc2)

**Comment by xessgamedev** [comment]
It seems that the plugin source or binary is not updated, please help to confirm if the files are replaced and plugin binaries re-built.

**Comment by Nerwy** [comment]
I just rebuilt the plugin with the fix and it does indeed work. Are you planning to add this fix to an official build anytime soon?

**Comment by xessgamedev** [comment]
Yes, definitely, and together with other bug fixes and new features.
Thank you for reporting and helping to verify.
