### ISSUE TITLE
Unreal Engine 5.1?

### ISSUE THREAD

**Issue by mrquantumoff** [GameTechDev/XeSSUnrealPlugin#2]
Does the 5.0 version work together with 5.1 or do we need another version for 5.1? If so, do we have an ETA?

**Comment by sunzhuoshi** [comment]
Sorry, 5.0 version doesn't work with 5.1, the code is done and under internal testing, hopefully make it public in March.

**Comment by xessgamedev** [comment]
Unreal 5.1 supported in https://github.com/GameTechDev/XeSSUnrealPlugin/releases/tag/v1.2.6
