### ISSUE TITLE
Lack of editor viewport and standalone game launch support with Unreal 5.1 or above

### ISSUE THREAD

**Issue by mrjimeneprime** [GameTechDev/XeSSUnrealPlugin#3]
Deleted and Solved

**Comment by xessgamedev** [comment]
Thank you for posting here.

We're trying to make it work perfectly in editor viewports. Hopefully done with XeSS SDK 1.2.

Currently , there're a workaround solution for "Play In Editor", but it will change editor settings and make things complicated duo to various Unreal editor settings related.
We can try to add this workaround in next release, and it will be great if you can help to test it and give us any feedback.

**Comment by mrjimeneprime** [comment]
Absolutley. I would love to give my feedback on the XeSS system and plugin.
I'm a big Intel and game market enthusiast. 
I'll give my email incase you want to send any test versions to me.
mrjimenezprime@gmail.com
I've been keeping up with Intel for years and I have noticed how **on top
of it** you guys have been when it comes Arc, fixing every problem your customers
throw back at you.  At the moment, bad optimizations are a plague in the PC gaming market.
This is a battle of the perfomance upscalers. The best looking one will win.
**I want Intel to be in the lead.**
I'll keep most of the Unreal Versions downloaded to test any plugin pieces _sent_ appropriately. 
Thank you guys for keeping strong and focused.

**Comment by mrjimeneprime** [comment]
I'm forgot to mention I'm also I game dev working on a title. 
Currently I can't **even use or test XeSS** because 
of the amount of resources being taken by the editor and the stand alone game window. 
I can only get 3-5 fps and my whole computer stutters. 
I have a i5 10600k with 15gb of RAM.  Dual GPU Z series motherboard. (I only have 1 GPU atm)
At the the moment I'm borrowing a 3060 from a family member who doesn't mind me using it in my pc.
That's why having this in editor needs to be implemented asap.  
I'm open to any solutions for the moment.

**Comment by xessgamedev** [comment]
> I'm forgot to mention I'm also a game dev working on a title. Currently I can't **even use or test XeSS** because of the amount of resources being taken by the editor and the stand alone game window. I can only get 3-5 fps and my whole computer stutters. I have a i5 10600k with 15gb of RAM. Dual GPU Z series motherboard. (I only have 1 GPU atm) At the the moment I'm borrowing a 3060 from a family member who doesn't mind me using it in my pc. That's why having Xess in editor needs to be implemented asap. I'm open to any solutions for the moment. But for now, its unusable.

Got it, that's valuable feedback for us.
We'll notify you once it is supported in Editor.

**Comment by xessgamedev** [comment]
The new release is available: https://github.com/GameTechDev/XeSSUnrealPlugin/releases/tag/v1.2.10
Please have a try and welcome any feedback. @mrjimeneprime

**Comment by mrjimeneprime** [comment]
This is great. I tested it and I'm very satisfied with the simplicity _of the implementation_. 
Now that I have been able to test out Xess I can give my feedback on it.
I am locked at 1080p on my 3060. So I can't raise my resolution because framerates will drop to much and I don't get the inherent Xe hardware version of Xess(HW-XESS). 

Performance seems fine but it seems clear that it's not meant for upscaling to 1080p or Anti-Aliasing at 100% Screen percentage (which I found was not possible unlike TSR allows). 

I also get significant ghosting even on Ultra-Quality which is also the case for DLSS. I cannot show our project, but the best example would be city sample.  I will be making an attempt to run Xess at 4k and test out the results.

Our game takes place in a city with Metahumans and hair ghosts with both DLSS and SW-XESS  at 1080p.  I'll update my feedback asap. UE5.2 seems to have an issue so I will be testing on 5.1 next.

**Comment by xessgamedev** [comment]
There's a workaround for Unreal 5.1 and above  if you can't use blueprint:
1. Get screen percentage required via `r.XeSS.ScreenPercentage`
2. Set `r.ScreenPercentage` with the value got

Please note: `r.XeSS.ScreenPercentage` may be removed in future versions.

**Comment by mrjimeneprime** [comment]
In launch game the workaround does not work. Tried all correct values with quality presets.

**Comment by mrjimeneprime** [comment]
That work around is fine in my opinion but this is the result (Not our project but same results)
had to turn down settings for vram. 
https://drive.google.com/file/d/1qEVL1Lao2alblW2axhZkH1N8k-N6uZ9e/view?usp=share_link

When anything moves it looks like it's motion vectors are on the right side of the object. 

Replicate by launch game by the right clicking uproject file, and use r.SetRes 3840x2160f and then do the Xess workaround.
