### ISSUE TITLE
Unreal 5.1.1 compatible?

### ISSUE THREAD

**Issue by oscarbg** [GameTechDev/XeSSUnrealPlugin#4]
as it says 5.1 only compatible..

**Comment by mrjimeneprime** [comment]
I'm pretty sure you can just put the Xess folder inside the plugins folder and it should work fine.

**Comment by xessgamedev** [comment]
Yes, but the pre-built package works with Unreal 5.1.1 only, not with Unreal 5.1.0.
You could upgrade to Unreal 5.1.1, or build plugin from source code by yourself to work with Unreal 5.1.0.
