### ISSUE TITLE
Unreal Engine 5.4

### ISSUE THREAD

**Issue by omegartlx** [GameTechDev/XeSSUnrealPlugin#8]
Hi
I dont know if you guys know yet but Unreal Engine 5.4 came out and it would very helpful if this got updated.

**Comment by xessgamedev** [comment]
Thank you so much for your reminder. Support for Unreal 5.4 is currently in progress.. Hopefully available in next week.

**Comment by xessgamedev** [comment]
Here is the release with Unreal 5.4 support: https://github.com/GameTechDev/XeSSUnrealPlugin/releases/tag/v1.4.7
Welcome any feedback.
