### ISSUE TITLE
1.3 on 4.27 support returns false

### ISSUE THREAD

**Issue by Hevedy** [GameTechDev/XeSSUnrealPlugin#9]
Hello there, first of all I have to say, thank you so much for support older engine version, I'm on a custom 4.27 branch, implemented XeSS 1.3.0 just as other upscalers on my game/engine version, turns out the function "UXeSSBlueprintLibrary::IsXeSSSupported()" called via C++ (just as I do with other upscalers) is returning false all the time, on editor, shipped and debug packaged version.
Even if I call it randomly via Blueprints from UMG is still returning false later.

Note I'm on a Nvidia series 3000RTX unsure if is related, just didn't made any call to the plugin, is enabled and implemented on C++ but not doing any call at the moment, I'm expecting that first bool returns true in order to enable the settings etc.

Bests.

**Comment by xessgamedev** [comment]
Would you please share the log file?

**Comment by Hevedy** [comment]
Oh okay I think found the issue without the need to send the log, found in the log that DX11 isn't supported when is the setting in the project, kind of sad given the other solutions works with it.
```
[  0]LogXeSS: XeSS plugin version: 1, version name: 1.4.7
[  0]LogXeSS: Current RHI D3D11 doesn't support XeSS, please switch to D3D12 to use it
```

**Comment by xessgamedev** [comment]
Sorry, DX11 is still not supported.
If no further issue, please close it, thanks.
